# Generated by Django 4.1 on 2022-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='tag',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
